# AWS
# AWS_ACCESS_KEY_ID: 'AKIAIGZWIR6GB56FDLPA'
# AWS_SECRET_ACCESS_KEY: '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'

# LOSANT CONFIG
LOSANT_APP_ID: '59b9ac8ebc9c9b0007659ade'
LOSANT_ACCESS_KEY: '17b39354-6e6b-4145-af17-01d55a43e834'
LOSANT_ACCESS_SECRET_KEY: 'e607a2eeddb1db98dc6404a8bb2f27ff0194cfc5a6ab02dc8a0cad6f6f83abf7'
LOSANT_API_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1OWRhYjE4ZTRiMWIwOTAwMDdiNGFlNmQiLCJzdWJ0eXBlIjoiYXBpVG9rZW4iLCJzY29wZSI6WyJhbGwuQXBwbGljYXRpb24iXSwiaWF0IjoxNTA3NTA0NTI2LCJpc3MiOiJhcGkuZ2V0c3RydWN0dXJlLmlvIn0.OWK8XJoW1X_3vFxQFq91dU2q_askzxiEbW9585VcBJc'